version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: bootcamp
      MYSQL_DATABASE: bootcamp
      MYSQL_USER: bootcamp
      MYSQL_PASSWORD: bootcamp
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    restart: always
  minio:
    image: quay.io/minio/minio:RELEASE.2022-01-08T03-11-54Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  mysql:
  minio:
